### PR TITLE
Redirects documentation away from readTheDocs.org

### PR DESCRIPTION
**Pull request by sgpearse**
This redirects our readTheDocs.org documentation to static html that is hosted on a github page [in a new repository](https://github.com/NCAR/VaporWebsite).

This also adds documentation for the python API, which can be seen [here](https://ncar.github.io/VaporDocumentationWebsite/pythonAPIReference/classReference.html).

### CODE REVIEW

**Review by NihanthCW — APPROVED** [review]

**Comment by sgpearse** [comment]
@stasj I added you as a reviewer since this regards the new Python API docs which you can find in the PR description.

**Review by StasJ — COMMENTED** [review]
Looks good. Just a few notes:
- vapor.utils is user facing
- some modules, like vapor.common and vapor.cmake, are completely empty
- Having the classes like FlowRenderer in the nav tree would be useful. Currently you have to scroll through a very long page to find a renderer.

**Comment by sgpearse** [comment]
@sgpearse will address stas' requests #1 and 3, and we will wait for [VAPOR's ticket #3350](https://github.com/NCAR/VAPOR/issues/3350).

**Comment by NihanthCW** [comment]
I am comfortable with us merging this PR at this stage. This should also allow us to gather feedback from the users and identify any areas of improvement. Thanks Scott!

**Pull request merged**
